### ISSUE TITLE
Get proper logo from ENERGY STAR

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#11]

**Comment by mgd722** [comment]
What do you mean when you say 'proper logo'?  Is the blue one not correct?  There are plenty of [vector versions](https://www.google.com/search?q=energy+star&rlz=1C1GGGE___US612US612&espv=2&biw=1920&bih=979&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMIyse69JyXxwIVxTuICh0Z-Axr#tbm=isch&q=energy+star+logo+vector) of it out there if we just need to scale it down to an appropriate size/format.

**Comment by raemacias** [comment]
Katrina is getting a logo directly from Energy Star so it's all nice and legal.

**Comment by mgd722** [comment]
Oh, right.  That would make sense.

**Comment by mgd722** [comment]
Any closing notes on this?  What's the outcome?

**Comment by raemacias** [comment]
Hey Mike - she actually posted that in the Flowdock. We can't make the logo into a circle, and we are making the blue dots the same color as the logo and there are guidelines. I'm replacing the official logo with what we have in there and the blue dot color so I'll be pushing those changes up later. 
It looks like you're listed on flowdock, here is the site:  
https://www.flowdock.com/app/cfa-brigades/denver-energy-efficiency

**Comment by mgd722** [comment]
Oh man...too many places!  Thanks Rae; I'm still getting used to using FlowDock/Waffle for collaboration.

**Comment by katrinamanagan** [comment]
I was going to post here, but couldn't figure out how to attach the logo here so went with flow dock.  I should have also made a note here.  Apologies for the confusion!

**Comment by mgd722** [comment]
![image](https://cloud.githubusercontent.com/assets/12187845/9235205/75a9901a-40fa-11e5-910e-f2c7bbc3e460.png)
You can just copy/paste images like normal.  This will allow other people/cities (who might not have access to the flowdock) can see this as well.

**Comment by katrinamanagan** [comment]
Great!

**Comment by raemacias** [comment]
Mike - if you want to take a look, I just did a pull request for the replaced "official" logo and blue dot and I added a comment to the JS about not being allowed to change the logo.
