### ISSUE TITLE
Mock-up the fields that pop up when someone clicks on a building.

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#12]
Dave is finalizing the mock up so info for each building looks like the following:

Green and ENERGY STAR buildings, small pop-up:
Building Name
Building Address
Picture from google
Blue box with ENERGY STAR score
If ENERGY STAR certified in the prior year, include ENERGY STAR logo on the pop-up
Number of views
Number of FB shares
Tell your friends you’re in a building managing for efficiency! (button here to share on facebook)

Green and ENERGY STAR buildings, large info block at bottom:
Building Name
Building Address
Picture from google
Blue, Red and Green boxes – show ENERGY STAR score, EUI, Carbon Footprint
If ENERGY STAR certified in the prior year, include ENERGY STAR logo in the box
Number of views
Number of FB shares
Tell your friends you’re in a building managing for efficiency! (button here to share on facebook)
Property Type:
___ square feet:
Built in ____
Building Website
Other green certifications/programs: if the number 1 is in columns N-W then list the column header here.  We don’t have permission to use these logos.
Top Energy Efficiency Strategies: add text here if present in the column

Gray with a null mark, small pop-up:
Building Name:
Building Address:
picture from google
Blue box for ENERGY STAR, with question mark in the middle instead of score. 
Ask the building to get on the map! (link to pop up draft email to property manager.)
Number of views
Number of FB shares
Tell your friends you’re helping to fill in the map! (button here to share on facebook)

Gray with a null mark, large info block at bottom:
Building Name:
Building Address:
picture from google
Blue, Red and Green boxes – show ENERGY STAR score, EUI, Carbon Footprint – all with question mark in the middle instead of score. 
Encourage the building owner/manager to enroll the building in Denver's benchmarking program at www.denvergov.org/cep.  Click here for a draft email to your property manager (you’ll need to look up their email address).
Number of views
Number of FB shares
Tell your friends you’re helping to fill in the map! (button here to share on facebook)
Property Type:
___ square feet:
Built in ____
Other green certifications/programs: if the number 1 is in columns N-W then list the column header here.  We don’t have permission to use these logos.

**Comment by mgd722** [comment]
I actually think this already looks pretty good as is.  The only thing I'd change is maybe to have the popup title be the building name (in bold) and the address under it (both without field names).  I don't think I described this very well in text but something like this:
![image](https://cloud.githubusercontent.com/assets/12187845/9183272/5b8fa9b6-3f6b-11e5-83d1-0fe06ced8074.png)

Might be a bit cleaner?  I can get at this if it's something we're interested in.

**Comment by katrinamanagan** [comment]
Hi Mike - I think your suggestion is great!  There are a few fields missing that we need to add, so I need to go through the spreadsheet and figure out which of those really matter.  But, cleaning up the look is a great start.  I also have pictures of many of the buildings.  Do you know of an easy way to read jpg files somewhere?  Maybe we can talk about that tonight.
-Katrina

**Comment by mgd722** [comment]
If you host them on our server then we can just link to them through the Maps API.  We can discuss it tonight.
