### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by wdoug** [codefordenver/denver-sustainability#17]
As someone who finds this project on GitHub, I want to know what the license is so I can decide weather to contribute / copy the project, etc.

Licenses define the legal framework for the project.

**Comment by wdoug** [comment]
Here is a simplified guide to a series of common options: http://choosealicense.com/

**Comment by wdoug** [comment]
Check discussion here: https://waffle.io/codefordenver/org/cards/55ac29280dc19e1500cdd2b8

**Comment by katrinamanagan** [comment]
Went with MIT license.
