### ISSUE TITLE
Legend and map:  Rules for the markers

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#2]

**Comment by katrinamanagan** [comment]
Will move into the 'ready' category once the data is geocoded and cleaned up.

**Comment by katrinamanagan** [comment]
The following are definitions of what buildings should pop up for each marker:

ENERGY STAR certified, >50,000 sq ft -  buildings certified in the previous calendar year should be blue (now need 2014 certification, in 2016 that will be for 2015).

Benchmarked, >50,000 sq ft - any building on the list of benchmarked buildings (list of 115 buildings). Not all of these will have an ENERGY STAR score, though most will.  These were not ENERGY STAR certified in the previous year.

Non-benchmarked, >50,000 sq ft - the remaining buildings that were not on the list of benchmarked buildings list.

ENERGY STAR certified, <50,000 sq ft  - same definition as above, just smaller buildings

Benchmarked, <50,000 sq ft  - same definition as above, just smaller buildings

Non-benchmarked, <50,000 sq ft  - same definition as above, just smaller buildings

**Comment by mgd722** [comment]
Implemented with #49
