### ISSUE TITLE
Build database, structure for the data, what form it will take on the back end, tables. Button for upload. Schema for tables.

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#22]
Make sure the City staff can upload new buildings to the base data set of 6000 buildings (we'll need to add a few every year for new construction, etc).  Also, we'll need to be able to regularly upload new energy performance data for buildings as buildings enroll and share their ENERGY STAR scores with the City.

**Comment by mgd722** [comment]
Database and data structure built by @jdepree using MySQL; remaining issues duplicated in #37.
