### ISSUE TITLE
Make it mobile friendly

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#30]
margins on the sides are critical for scrolling in the page

**Comment by raemacias** [comment]
Can anyone tell me what we want the sidebar to do for mobile, just to be smaller on the side or to disappear altogether?

**Comment by mgd722** [comment]
I'd vote to have the ability to hide the sidebar once you've finished reading it.

**Comment by katrinamanagan** [comment]
That makes sense to me.

**Comment by raemacias** [comment]
Also check out Jeff's suggestion from Flowdock since I asked the same question over there: which is this:
Here is one option with a bottom-loading info bar (it resizes to fit on mobile screens).  http://www.foodnextdoor.org/denverenergystars/

**Comment by katrinamanagan** [comment]
I defer to all of you on this one, but Jeff's suggestion looks good!

**Comment by D3s1gnerUX** [comment]
I agree with Jeff. To extend, how about turning the sidebar text into an "about" section ("what we do", "what does all this mean"?, etc.) in mobile view, that can stack below the map window. Users prefer scrolling on mobile to links, and we can always have the "About" still be an anchored link from sticky navigation (have you guys discussed top of the screen navigation vs bottom of the screen navigation?)

One other question... maps on mobile devices are notorious for taking up the full screen, and then any attempt to vertically scroll the page ends up scrolling the map, essentially trapping the user on the map. One way this can be avoided by creating generous map margins, or adding an "back to top" or "up" to the sticky navigation.

I'm absolutely new to the project, so apologize in advance if I'm talking about something you've already covered. 

I was going to mock up a web and mobile main page view, if that would still be of value, and if it hasn't already been done.

Dave

**Comment by raemacias** [comment]
I don't think we discussed that yet Dave, so I think your ideas are great, and I think you should go ahead with the mock up and we can all look at it on Monday if it's ready by then.

Also - we were going to add the legend to the bottom of the sidebar (when it was moved to a sidebar) in the white space under the text. So we'll need to see where to put that legend now.

**Comment by mgd722** [comment]
@D3s1gnerUX I think your mock up would definitely be valuable-- we haven't really come to much of a design consensus because none of us are designers.

**Comment by raemacias** [comment]
@katrinamanagan Should we have a "hamburger menu" on the mobile view so we can have different pages where everything is explained like FAQs, contacting your leasing manager, and any other information we want to provide?

**Comment by mgd722** [comment]
I like the idea of a hamburger menu for mobile.  I just opened it on my iPhone and it was all over the place, so I think some scheme of organization is necessary.

**Comment by raemacias** [comment]
I thought so too. I will go ahead and do one then. I don't have a timeframe on when it can be done, but I'll work diligently at it for sure.

**Comment by katrinamanagan** [comment]
I think that will work well if you guys think so!  I trust your your judgement on making a user friendly web page.

**Comment by milkman97** [comment]
Hey, i've been helping nick with making your site more mobile friendly with the materalize frame work, and i rebuilt the navbar so it can be mobile friendly with the hamburger icon. Although, to do so, i had to add the full materalize.js file to get it working. Any time i try to update the min file, it causes the site the map to not show. If anyone can help, that would be much appreciated.

**Comment by raemacias** [comment]
@milkman97 Have you gotten any help on this yet?
