### ISSUE TITLE
Legend:  Add correct building marker icons.

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#33]
6 markers, description followed by title:

ENERGY STAR logo - ENERGY STAR certified 2014, >50,000 sq ft.
 Green circle - Benchmarked buildings, >50,000 sq ft.
 Gray question mark in circle - un-benchmarked, >50,000 sq ft.
 small blue dot - ENERGY STAR certifeid, <50,000 sq ft
small green dot - Benchmarked buildings, <50,000 sq ft.
small gray dot - un-benchmarked, <50,000 sq ft.

**Comment by katrinamanagan** [comment]
https://upload.wikimedia.org/wikipedia/commons/9/93/Torchlight_help_gray.png  
Link for gray question mark.

**Comment by D3s1gnerUX** [comment]
I'd like to make sure that all of the icons match styles. We don't want one to be beveled and one not, one with a faux 3D treatment and one flat, etc. Modern web/mobile design has obviously moved toward flat design, and the good news here is that this sort of simple treatment is much more durable in the face of 'fashion' trends.

We can look specifically for a batch of icons which look the same on a pay site, or I can create them (except for the Energy Star logo, of course).

Does somebody know the specs for the icons/graphics we're using on the map?

If not, I can research.

Dave

**Comment by raemacias** [comment]
We didn't really use any required or exact specs, we just put in the official energy star logo which cannot be modified, and then we should have a blue dot that is that same color Cyran which is 00AEFF color, then we have a green circle and a green dot, and then we have a gray circle (which we were thinking of having as a circle with a question mark, and I think a gray dot too, but wasn't sure. We sized them however we thought might look okay, but not specific to the project. The circles should be larger than the dots - they are based on the building size of over and under 50,000 sf.

**Comment by mgd722** [comment]
Current icons also kind of pixelate/alias on my retina Mac.  The Google Maps API supports SVG paths as marker symbols, so we could do that (particularly if we're going with the flat design that Dave suggested).

**Comment by katrinamanagan** [comment]
Rae's description is exactly right.  Help with a flat design for the markers would be most welcome - leaving the ENERGY STAR logo and general color goal the same.

**Comment by katrinamanagan** [comment]
Let me know if you need any further or clearer description of the 6 types of markers.

**Comment by raemacias** [comment]
I pushed up a basic legend for the correct marker icons but it still needs some styling work done on it.

**Comment by raemacias** [comment]
We ended up going with the grey circle with the line through it, but the markers are clearly identified now.
