### ISSUE TITLE
Decide on clustering

### ISSUE THREAD

**Issue by jdepree** [codefordenver/denver-sustainability#35]
I'm not convinced clustering is the way to go here, but this is the default implementation:
http://www.foodnextdoor.org/denverenergystars/indexCluster.php

Do we want clustering?  Would we want some alternative clustering visualization?  Maybe something that shows the composition of the cluster (i.e., number of types of different kinds of buildings)?

**Comment by mgd722** [comment]
This feels too aggressive to me.  Too many bright contrasting colors.

**Comment by katrinamanagan** [comment]
I agree, clustering might not be the best fit.  In part, because the clusters can't show how many of each building type are in the cluster, so the three different colors/designations are lost.  Hmmm.

**Comment by katrinamanagan** [comment]
No clustering, instead will filter on icon sizes and types.
