### ISSUE TITLE
Clean up v2 branch

### ISSUE THREAD

**Issue by mgd722** [codefordenver/denver-sustainability#36]
@jdepree, I don't think we should merge your v2 branch without cleaning it up a bit first.  We don't really need the v1 code anymore and it'll be preserved in this repo's history, so I think it would be better if we removed it from your branch and used your v2 folder as the repo's root.  Do you have time to do this?  I can do it otherwise, but I figured that you have a more complete understanding of your code.  After it's clean I think we're good to submit a PR for it.

**Comment by mgd722** [comment]
Okay so I guess I'll just do this.

**Comment by mgd722** [comment]
During my brief attempts to get this to work, the markers still didn't load.  I'm cleaning up the branch for now but we can discuss it tonight.

**Comment by raemacias** [comment]
Let me know if I can do any of the clean-up stuff on this. I'll be there tonight as well.
