### ISSUE TITLE
Non-map text

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#4]
On the bottom of the map: 

5.5% of buildings enrolled (show on thermometer) of Denver has benchmarked with ENERGY STAR. Help us get to 100%!

What is an ENERGY STAR score? (opens text when clicking: The 1-100 ENERGY STAR score benchmarks, or measures, the energy performance of buildings. 50 is the national average score, and any score above 75 can qualify for ENERGY STAR certification.)

What is EUI? (opens text when clicking: The energy use intensity shows the energy intensity in kbtu per square foot.)

Link for Frequently Asked Questions doc to open.

Do More! Make your own space energy efficient and get the company where you work to sign up for our Lease for Efficiency Challenge. http://www.denvergov.org/environmentalhealth/EnvironmentalHealth/EnvironmentalQuality/DenverCityEnergyProject/TenantsLeadingtheWay/tabid/445817/Default.aspx

**Comment by katrinamanagan** [comment]
Total clicks on the map: ___

4.6% (show on thermometer) of Denver has benchmarked with ENERGY STAR. Help us get to 100%!

What is ENERGY STAR? (opens text when clicking: The 1-100 ENERGY STAR score rates the energy performance of buildings. 50 is the national average score, and any score above 75 can qualify for ENERGY STAR certification.)

What is EUI? (opens text when clicking: The energy use intensity shows the energy intensity in kbtu per square foot.)

Do More! Make your own space energy efficient and get the company where you work to sign up for our Lease for Efficiency Challenge. http://www.denvergov.org/environmentalhealth/EnvironmentalHealth/EnvironmentalQuality/DenverCityEnergyProject/TenantsLeadingtheWay/tabid/445817/Default.aspx

**Comment by mgd722** [comment]
Obviously there is no longer a white column on the left.  Splash screen?

**Comment by mgd722** [comment]
@katrinamanagan, @D3s1gnerUX : any idea where this text should go given the current layout of the page?  The empty white space in the bottom right of the bottom card will be going away when the site is mobile.

**Comment by katrinamanagan** [comment]
@mgd722  I think the 'help us fill in the map' part is in the side-bar.  Could the rest go there as well as text that links to or pops up more info when clicked on?  The text in the sidebar might be: 'What is an ENERGY STAR score?', 'What is EUI?' and 'FAQ'
Do you have a latest version of the map that you could show me so I can think about where it best fits? 

Do More!

**Comment by katrinamanagan** [comment]
@mgd722 I meant 'Do More!' to be a 4th bit that would link out/pop up more information.

**Comment by raemacias** [comment]
@katrinamanagan and @mgd722 This is what I was working on last night and will continue tonight...I was putting that at the bottom of the map and text that is there, using the links to pop up the EUI and FAQ. I'll see what I can put together and push it up here tonight...then Katrina, it will be live using the link that goes through Heroku, which is this: http://denver-sustainability.herokuapp.com/

**Comment by katrinamanagan** [comment]
@RaeRae961 Awesome!  Sounds good!

**Comment by raemacias** [comment]
@katrinamanagan @mgd722 Please check the latest bottom of the map info. I added little popups for the two definitions, but we are missing FAQs even though it looks like it's a link. Katrina - do you have FAQs?

**Comment by katrinamanagan** [comment]
@RaeRae961 I'm still writing the FAQ's, but will aim to have them drafted by the time I see you all November 30th!

**Comment by raemacias** [comment]
@katrinamanagan Not sure if you saw my comment in flowdock but I don't think I'll be there tonight...and Mike won't be either, he had an unexpected trip out of the country.

**Comment by raemacias** [comment]
@katrinamanagan I would say yes to wait, but there are others working on the project too, so I just don't know.

**Comment by katrinamanagan** [comment]
@RaeRae961 I am going to plan to wait until next week.  But - if anyone has any questions tonight feel free to call my cell phone anytime 202-355-3148 or skype me at katrina.managan
