### ISSUE TITLE
Get hi res city energy project logo in png

### ISSUE THREAD

**Issue by mgd722** [codefordenver/denver-sustainability#45]

**Comment by mgd722** [comment]
We need a higher resolution version of [this](https://cdn.evbuc.com/images/11901320/119412759767/3/logo.jpg) in .png (and ideally with a transparent background).  This is going in the header per Dave's mockups.

**Comment by katrinamanagan** [comment]
![denver city energy project logo](https://cloud.githubusercontent.com/assets/12819177/10462943/b4ed3e0a-719e-11e5-9a2e-671d845d309c.jpg)
Will this logo work?  I also have it in .ai and .eps formats

**Comment by mgd722** [comment]
Awesome.  If you send along the .ai version I can convert it to .png with a transparent background.

**Comment by katrinamanagan** [comment]
The .ai file type isn't supported here, but I'll email it to you now at mgd722@gmail.com Is that right?

**Comment by mgd722** [comment]
Yup, I got it.  Thanks!
