### ISSUE TITLE
Gray buildings filter too slowly; probably too many of them

### ISSUE THREAD

**Issue by mgd722** [codefordenver/denver-sustainability#48]
We might need to cut down on the number of gray buildings visible on the map; it takes forever to load.  Is this acceptable, @katrinamanagan ?  Clustering might increase performance, but I'm not 100% on that.

**Comment by katrinamanagan** [comment]
@mgd722 We could remove all gray buildings that are under 50,000 sq ft if you want.  I think that would be fine!  We'll keep the smaller ones that are green.

**Comment by katrinamanagan** [comment]
Sorry for the slow response - I was out of town on vacation.  I'm back now and available anytime!

**Comment by mgd722** [comment]
No worries!  I'll try to cut out the smaller gray markers and see if it makes a difference.  If not, I'll ask around tonight and see if anyone else knows a good way to manage this.

**Comment by katrinamanagan** [comment]
Great!

**Comment by mgd722** [comment]
Solved by #51
