### ISSUE TITLE
Filter Map Markers

### ISSUE THREAD

**Issue by nickpalmer789** [codefordenver/denver-sustainability#62]
Filtering map markers may make it easier for users to see which buildings actually have ratings, as many of them don't have a rating at all. This may also help with performance issues.

**Comment by mgd722** [comment]
What do you mean by this?  Markers can currently be filtered by clicking legend items.

**Comment by nickpalmer789** [comment]
Didn't realize that they could be filtered that way. Maybe some indicator of that would be nice. Just a backlog thing though.
