### ISSUE TITLE
Update Legend

### ISSUE THREAD

**Issue by raemacias** [codefordenver/denver-sustainability#66]
Remove text at bottom "Buildings less than 50k square feet..." then add text "Help us fill the map..." and scale from mock up here: https://drive.google.com/drive/folders/0B-Zrn2LpwNnRflhkMWs3cFRibFNCQno0ei1OV25uMVRsT19URVpZZXN2LTFjcHpwSjIwNWc 
and then add total map views.

**Comment by raemacias** [comment]
The scale would be a "progress bar" or preloader. (in materialize docs)

**Comment by raemacias** [comment]
Tristan - I assigned this ticket to you since you did the other subtask. When you go on here in the waffle, you can assign tasks to yourself or others so that we know who is taking care of each item. Great job on the legend work.

**Comment by milkman97** [comment]
Thanks! Well I added the progress bar to the legend and made it mobile friendly. Although, when trying to figure out the back end stuff where I could get the length of the arrays that hold the blue or green building objects, I get absurd numbers like 2125 energy efficient building in the console. To which, i can physically count all the buildings and change the variable in the index to have it be accurate for the time being while we work on making it be able to update its own-self.

**Comment by milkman97** [comment]
actually i think i finally got it

**Comment by milkman97** [comment]
never mind i fixed it all haha
