### ISSUE TITLE
Investigate asynchronous bug

### ISSUE THREAD

**Issue by wdoug** [codefordenver/denver-sustainability#75]
As a user I want the site to load and run properly every time.

Currently there appears to be an issue with improper verification that data is loaded before bootstrapping the site. Since something that is required isn't always done loading when it is called for the site occasionally blows up.

**Comment by nickpalmer789** [comment]
Do you know if there is a specific situation in which this bug occurs?

**Comment by wdoug** [comment]
@nickpalmer789, @jdepree mentioned something about one issue where the data loads and tries to be put on the map before the map is initialized. 
I noticed a few different console errors when just repeatedly loading the page, so I suspect there are a couple (potentially related) bugs. I didn't record them, but that would probably be a good first step.

**Comment by wdoug** [comment]
Let me know if you try to reproduce them and can't.

**Comment by nickpalmer789** [comment]
I have observed the same console errors, and have now reproduced the bug. I will do my best to find the source of the problem in the next few days.

**Comment by wdoug** [comment]
:+1:

**Comment by nickpalmer789** [comment]
I think that I have made an edit that I am pretty sure has fixed the error. Look in the branch nick/asynchronous _bug for the fix that I implemented.

**Comment by wdoug** [comment]
Looks like the bug was fixed in #79. I thought there might have been some other issues as well, but don't seem to have a problem currently. I'm curious how that was even working part time previously without the `js/initMap` being explicitly pulled in.
