### ISSUE TITLE
https mixed content bug

### ISSUE THREAD

**Issue by wdoug** [codefordenver/denver-sustainability#84]
Right now when trying to load the page over `https` we are trying to load the data over http (http://foodnextdoor.org/denverenergystars/php/getGeohashedBuildings.php). Most(?) browsers will block this insecure content on a http site.

**Comment by wdoug** [comment]
I'm guessing we will have to change our hosting of the backend to make this work for loading the data over https.

**Comment by jdepree** [comment]
Probably - why is the front-end being accessed with https?

**Comment by wdoug** [comment]
I am going to close this as it should be fine to just access with `http`.
