### ISSUE TITLE
Create separate in-map and bottom card info windows

### ISSUE THREAD

**Issue by katrinamanagan** [codefordenver/denver-sustainability#9]

**Comment by raemacias** [comment]
Make sure it works on mobile

**Comment by mgd722** [comment]
Possibly reworking info window to make it smaller and keeping it in the map canvas.

**Comment by mgd722** [comment]
![screen shot 2015-08-24 at 19 16 05 copy](https://cloud.githubusercontent.com/assets/12187845/9456471/844ce06e-4a95-11e5-8c02-91efcd7885d2.jpg)

@katrinamanagan, @D3s1gnerUX, old info windows (as they appeared in infobox-pizazz branch)

**Comment by mgd722** [comment]
Going with two infowindows--one small in-map pop-up with critical information that links to a bottom card with more detailed data.

**Comment by mgd722** [comment]
@katrinamanagan and @D3s1gnerUX, based on yesterday's meeting, is this still something we're interested in implementing?  Again, really sorry I missed it.  I was out of town and it totally slipped my mind.

**Comment by katrinamanagan** [comment]
@Mike, its definitely something we want to implement.  Dave is doing another mock-up today/tomorrow based on my feedback on the first one.  As soon as we have that then this can move into the 'ready' pile to be implemented to look like the mock-up.

**Comment by mgd722** [comment]
Changing the bottom card to provide a more mobile-friendly experience; this now falls under #30
